import { ALL_FIELDS } from '@/data/intakeSteps';
import type { NormalizedIntake } from '@/engine/normalizeAnswers';
import type {
  ConfidenceBand,
  ConfidenceDeduction,
  ConfidenceResult,
  RouteAssessment,
} from '@/engine/types';

/* ------------------------------------------------------------------ *
 * Assessment confidence.
 *
 * Confidence describes how much the assessment had to work with. It is not a
 * probability that the recommendation is correct, and it is calculated
 * separately from feasibility so that a confident low score reads differently
 * from a tentative high one.
 *
 * A valid "None", a deliberate exclusion, and a clearly stated restriction are
 * information, not gaps: they never reduce confidence.
 * ------------------------------------------------------------------ */

const IMPORTANT_FIELD_IDS: readonly string[] = ALL_FIELDS.filter(
  ({ field }) => field.important === true,
).map(({ field }) => field.id);

export function determineConfidence(
  n: NormalizedIntake,
  route: RouteAssessment | null,
): ConfidenceResult {
  const deductions: ConfidenceDeduction[] = [];
  const missingInformation: string[] = [];

  /* --- unknown answers --- */
  const unknownCount = n.unknownFieldIds.length;
  if (unknownCount > 0) {
    const importantUnknowns = n.unknownFieldIds.filter((id) => IMPORTANT_FIELD_IDS.includes(id));
    const ordinaryUnknowns = unknownCount - importantUnknowns.length;

    if (importantUnknowns.length > 0) {
      deductions.push({
        reason: 'Questions the assessment leans on most were left unknown',
        points: importantUnknowns.length * 10,
        detail: `${importantUnknowns.length} of the most important questions are unanswered. Nothing was assumed in their place.`,
      });
    }
    if (ordinaryUnknowns > 0) {
      deductions.push({
        reason: 'Other questions were left unknown',
        points: Math.min(24, ordinaryUnknowns * 4),
        detail: `${ordinaryUnknowns} further questions are unanswered (capped at 24 points).`,
      });
    }
    missingInformation.push(
      ...n.unknownFieldLabels.slice(0, 12).map((label) => `Answer: ${label}`),
    );
  }

  /* --- vague answers --- */
  if (n.vagueFieldLabels.length > 0) {
    deductions.push({
      reason: 'Some written answers were too brief to interpret confidently',
      points: Math.min(15, n.vagueFieldLabels.length * 5),
      detail: `Brief answers: ${n.vagueFieldLabels.join(', ')}.`,
    });
    missingInformation.push(
      ...n.vagueFieldLabels.map((label) => `More detail: ${label}`),
    );
  }

  /* --- conflicting answers --- */
  if (n.conflicts.length > 0) {
    deductions.push({
      reason: 'Answers conflict with each other',
      points: Math.min(18, n.conflicts.length * 6),
      detail: n.conflicts.map((conflict) => conflict.description).join(' '),
    });
    missingInformation.push('A decision on each conflicting expectation listed in the assessment');
  }

  /* --- source of truth --- */
  if (n.dataDependent && !n.sourceOfTruthDefined) {
    deductions.push({
      reason: 'No authoritative source of truth has been identified',
      points: 10,
      detail: `The project depends on data, and the stated source of truth is "${n.sourceOfTruth}".`,
    });
    missingInformation.push('Which single source of data is authoritative');
  }

  /* --- unverified platform capability --- */
  if (route && route.technicalStatus === 'requires-verification') {
    deductions.push({
      reason: 'The recommended route depends on platform capabilities that have not been verified',
      points: 8,
      detail: route.technicalNotes.join(' '),
    });
    missingInformation.push('Confirmation of the platform capabilities listed under the recommended route');
  }

  /* --- unverified pricing --- */
  if (n.budgetTier === 'unknown') {
    deductions.push({
      reason: 'No budget was stated, and no prices are generated by this tool',
      points: 8,
      detail: 'Cost fit could not be checked against a stated budget.',
    });
    missingInformation.push('A budget range, even an approximate one');
  } else if (route && route.monthlyCost !== 'free-or-existing') {
    deductions.push({
      reason: 'Real pricing for the recommended route has not been verified',
      points: 5,
      detail: 'Subscription, platform, and hosting prices must come from the vendor, not from this tool.',
    });
    missingInformation.push('Written pricing for the shortlisted routes');
  }

  /* --- ownership --- */
  if (!n.ownerDefined) {
    deductions.push({
      reason: 'Project ownership is unclear',
      points: 6,
      detail: 'No owner was named, so accountability could not be assessed.',
    });
    missingInformation.push('Who owns this project');
  }

  /* --- maintenance responsibility --- */
  if (!n.troubleshooterDefined || !n.dataUpdaterDefined) {
    deductions.push({
      reason: 'Maintenance responsibility is unclear',
      points: 6,
      detail: [
        n.troubleshooterDefined ? null : 'No troubleshooter was named.',
        n.dataUpdaterDefined ? null : 'Nobody was named to keep the data current.',
      ]
        .filter(Boolean)
        .join(' '),
    });
    missingInformation.push('Who maintains the tool and who keeps the data current');
  }

  /* --- security requirements --- */
  if (n.sensitiveData && n.securityConcerns.length === 0) {
    deductions.push({
      reason: 'Security requirements are unclear',
      points: 8,
      detail: 'Sensitive information is involved but no security concerns or requirements were stated.',
    });
    missingInformation.push('The access rules for each kind of sensitive information');
  }

  const totalDeduction = deductions.reduce((sum, deduction) => sum + deduction.points, 0);
  const score = Math.max(0, Math.min(100, 100 - totalDeduction));
  const band: ConfidenceBand = score >= 80 ? 'high' : score >= 60 ? 'moderate' : 'low';

  if (missingInformation.length === 0) {
    missingInformation.push('Nothing material is missing from the intake.');
  }

  return {
    score,
    band,
    deductions,
    missingInformation,
    statement:
      'Confidence describes how much information this assessment had to work with. It is not a probability that the recommendation is correct, and it is not a measure of feasibility. Explicit "none" answers, deliberate exclusions, and stated restrictions are treated as information and never reduce it.',
    provenance: 'derived',
  };
}
