import { DataLabel } from '@/components/DataLabel';
import {
  BulletList,
  Callout,
  Disclosure,
  FactList,
  ReportSection,
  ScrollTable,
  StatusPill,
} from '@/components/report/primitives';
import type { Assessment, Risk, RiskScore } from '@/engine/types';
import { COST_CATEGORY_LABELS } from '@/engine/types';

/* Risk register, cost, and timeline. */

const RISK_TONE: Record<RiskScore, 'positive' | 'adequate' | 'watch' | 'weak' | 'critical'> = {
  1: 'positive',
  2: 'adequate',
  3: 'watch',
  4: 'weak',
  5: 'critical',
};

function RiskRecord({ risk, open }: { risk: Risk; open: boolean }) {
  const body = (
    <dl className="risk__detail">
      <div>
        <dt>Trigger</dt>
        <dd>{risk.trigger}</dd>
      </div>
      <div>
        <dt>Consequence</dt>
        <dd>{risk.consequence}</dd>
      </div>
      <div>
        <dt>Mitigation</dt>
        <dd>{risk.mitigation}</dd>
      </div>
      <div>
        <dt>Owner</dt>
        <dd>{risk.owner}</dd>
      </div>
      <div>
        <dt>Residual risk</dt>
        <dd>{risk.residualRisk}</dd>
      </div>
      <div>
        <dt>Evidence</dt>
        <dd>
          <ul className="risk__list">
            {risk.evidence.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </dd>
      </div>
      <div>
        <dt>Assumptions</dt>
        <dd>
          {risk.assumptions.length === 0 ? (
            'None.'
          ) : (
            <ul className="risk__list">
              {risk.assumptions.map((item) => (
                <li key={item}>{item}</li>
              ))}
            </ul>
          )}
        </dd>
      </div>
      <div>
        <dt>Blocks a route or verdict?</dt>
        <dd>{risk.blocks === null ? 'No' : `Yes — ${risk.blocks}`}</dd>
      </div>
    </dl>
  );

  return (
    <article className={`risk risk--${RISK_TONE[risk.score]}`}>
      <div className="risk__head">
        <h4 className="risk__title">{risk.label}</h4>
        <StatusPill text={`${risk.score} of 5 — ${risk.scoreLabel}`} tone={RISK_TONE[risk.score]} />
        <DataLabel compact label={risk.provenance} />
      </div>
      {open ? body : <Disclosure summary={`Full record for ${risk.label.toLowerCase()}`}>{body}</Disclosure>}
    </article>
  );
}

export function RiskRegisterSection({ assessment }: { assessment: Assessment }) {
  const { risks, highRisks } = assessment;
  const otherRisks = risks.filter((risk) => risk.score < 4);

  return (
    <ReportSection
      id="risk-register"
      intro={
        <p>
          All sixteen categories are scored from 1 (very low) to 5 (very high). Anything
          scored 4 or 5 is shown in full below, expanded by default. Ownership is always a
          named human role, never the AI.
        </p>
      }
      title="Risk register"
    >
      <h3 className="risk__section-title">
        Highest-priority risks ({highRisks.length} scored 4 or 5)
      </h3>
      {highRisks.length === 0 ? (
        <p>No risk scored above 3 (moderate) on the answers given.</p>
      ) : (
        <div className="risk-list">
          {highRisks.map((risk) => (
            <RiskRecord key={risk.category} open risk={risk} />
          ))}
        </div>
      )}

      <h3 className="risk__section-title">All risk categories</h3>
      <ScrollTable
        caption="Every risk category with its score, severity, owner, and whether it blocks anything"
        label="Risk summary table"
      >
        <thead>
          <tr>
            <th scope="col">Category</th>
            <th scope="col">Score</th>
            <th scope="col">Severity</th>
            <th scope="col">Owner</th>
            <th scope="col">Blocks</th>
          </tr>
        </thead>
        <tbody>
          {risks.map((risk) => (
            <tr key={risk.category}>
              <th scope="row">{risk.label}</th>
              <td>{risk.score} of 5</td>
              <td>{risk.scoreLabel}</td>
              <td>{risk.owner}</td>
              <td>{risk.blocks ?? 'Nothing'}</td>
            </tr>
          ))}
        </tbody>
      </ScrollTable>

      <div className="risk-list">
        {otherRisks.map((risk) => (
          <RiskRecord key={risk.category} open={false} risk={risk} />
        ))}
      </div>
    </ReportSection>
  );
}

export function CostSection({ assessment }: { assessment: Assessment }) {
  const { cost, routePlan, evidencePanels } = assessment;
  const isDemo = evidencePanels.demonstrationData.length > 0;

  return (
    <ReportSection
      id="cost"
      intro={
        <p>
          Cost is expressed as effort and categories. No hourly rate, subscription price,
          or hosting price is generated by this tool, and effort hours are not a quote.
        </p>
      }
      title="Cost"
    >
      <Callout title={cost.pricingStatement} tone="warning">
        <p className="no-margin">
          Every figure below is an estimate or a category. Confirm real prices with the
          vendor, platform, or supplier before committing to anything.
        </p>
      </Callout>

      <FactList
        items={[
          {
            term: 'Estimated effort-hour range',
            value: `${cost.effort.lowHours} to ${cost.effort.highHours} builder hours for ${routePlan.practical.name}`,
            provenance: isDemo ? 'demonstration-data' : 'estimate',
          },
          {
            term: 'Setup-cost category',
            value: COST_CATEGORY_LABELS[cost.setupCost],
            provenance: 'requires-verification',
          },
          {
            term: 'Monthly-cost category',
            value: COST_CATEGORY_LABELS[cost.monthlyCost],
            provenance: 'requires-verification',
          },
          {
            term: 'Maintenance-effort category',
            value: COST_CATEGORY_LABELS[cost.maintenanceEffort],
            provenance: 'estimate',
          },
          {
            term: 'External-support requirement',
            value: cost.externalSupportRequirement,
            provenance: 'derived',
          },
          {
            term: 'Cost confidence',
            value: `${cost.costConfidence} — based on how much of the pricing picture is known`,
            provenance: 'derived',
          },
        ]}
      />

      <BulletList heading="Main cost drivers" headingLevel={3} items={cost.mainCostDrivers} />
      <BulletList
        heading="Costs requiring verification"
        headingLevel={3}
        items={cost.costsRequiringVerification}
        tone="negative"
      />

      <Disclosure summary="How the effort range was derived">
        <BulletList items={cost.effort.basis} tone="muted" />
        <p className="text-sm">
          Effort is a range by design. It is an <DataLabel compact label="estimate" />, never a
          guaranteed quotation, and it changes with scope, support, and how much of the work
          is new to the builder.
        </p>
      </Disclosure>
    </ReportSection>
  );
}

export function TimelineSection({ assessment }: { assessment: Assessment }) {
  const { timeline, builderFit, cost } = assessment;

  return (
    <ReportSection
      id="timeline"
      intro={
        <p>
          Each phase is a range, not a date. A lower Builder Fit lengthens the calendar
          estimate; it does not reduce technical feasibility.
        </p>
      }
      title="Timeline"
    >
      <Callout title="Builder Fit and the timeline">
        <p className="no-margin">
          {timeline.builderFitEffect} Builder Fit for the practical route is{' '}
          {builderFit.score} of 100, and the effort estimate reflects that at{' '}
          {cost.effort.lowHours}–{cost.effort.highHours} hours.
        </p>
      </Callout>

      <ScrollTable
        caption="Estimated duration for each phase, with what the estimate depends on"
        label="Timeline phase table"
      >
        <thead>
          <tr>
            <th scope="col">Phase</th>
            <th scope="col">Time range</th>
            <th scope="col">Reachable on the recommended route?</th>
            <th scope="col">Main dependencies</th>
          </tr>
        </thead>
        <tbody>
          {timeline.phases.map((phase) => (
            <tr key={phase.id}>
              <th scope="row">{phase.label}</th>
              <td>
                {phase.bandLabel} <DataLabel compact label={phase.provenance} />
              </td>
              <td>
                {phase.achievable ? (
                  <StatusPill text="Yes" tone="positive" />
                ) : (
                  <StatusPill text="Not with this route" tone="caution" />
                )}
              </td>
              <td>
                <ul className="risk__list">
                  {phase.basis.map((item) => (
                    <li key={item}>{item}</li>
                  ))}
                </ul>
              </td>
            </tr>
          ))}
        </tbody>
      </ScrollTable>

      <FactList
        items={[
          {
            term: 'Deadline assessment',
            value: timeline.deadlineAssessment,
            provenance: 'estimate',
          },
          {
            term: 'Builder Fit impact',
            value: timeline.builderFitEffect,
            provenance: 'derived',
          },
          {
            term: 'Verification status',
            value:
              'Every duration here is an estimate derived from the answers given. None has been validated against a comparable delivered project.',
            provenance: 'requires-verification',
          },
        ]}
      />

      <BulletList
        heading="What these estimates depend on"
        headingLevel={3}
        items={timeline.factors}
        tone="muted"
      />
    </ReportSection>
  );
}
