import type { RouteId } from '@/engine/types';

/**
 * Build method versus final solution type.
 *
 * Several routes are easy to confuse because they answer different questions.
 * Claude Code and AI-assisted coding are *methods* of building. A custom hosted
 * web application is a *destination*. They are not mutually exclusive: you can
 * reach the same destination by either method, or use a method to build something
 * far simpler than a hosted application.
 */
export interface RouteDelivery {
  readonly buildMethod: string;
  readonly finalSolutionType: string;
  readonly hostingTarget: string;
  readonly builderRequirementSummary: string;
  /** Shown where the method and the destination are commonly conflated. */
  readonly overlapNote: string | null;
}

export const ROUTE_DELIVERY: Readonly<Record<RouteId, RouteDelivery>> = {
  'existing-saas': {
    buildMethod: 'Product selection and configuration, not building',
    finalSolutionType: 'Vendor-hosted product',
    hostingTarget: 'Provided by the vendor',
    builderRequirementSummary: 'Configuration and permission administration',
    overlapNote: null,
  },
  'chat-only': {
    buildMethod: 'Conversational use of an AI assistant, with nothing built',
    finalSolutionType: 'No system: a repeated manual workflow',
    hostingTarget: 'None',
    builderRequirementSummary: 'Clear prompting and review of every output',
    overlapNote: null,
  },
  'spreadsheet-doc': {
    buildMethod: 'Structuring a shared spreadsheet or document set',
    finalSolutionType: 'Shared file on existing storage',
    hostingTarget: 'Existing shared drive or cloud storage',
    builderRequirementSummary: 'Confident spreadsheet structuring and sharing settings',
    overlapNote: null,
  },
  'no-code': {
    buildMethod: 'Configuration on a no-code platform',
    finalSolutionType: 'Platform-hosted application',
    hostingTarget: 'Provided by the platform. Plan tier requires verification',
    builderRequirementSummary: 'Data modelling, permissions, and testing on the platform',
    overlapNote: null,
  },
  'claude-artifact': {
    buildMethod: 'Generated by Claude from a description',
    finalSolutionType: 'Single self-contained browser page, no backend',
    hostingTarget: 'None for review. Wider sharing is a separate decision',
    builderRequirementSummary: 'Describing the interface and reviewing what comes back',
    overlapNote:
      'A demonstration of a workflow, not the workflow itself. Nothing entered is retained.',
  },
  'ai-assisted-coding': {
    buildMethod: 'Writing and reviewing code with AI assistance',
    finalSolutionType:
      'Whatever you build: from a static browser page to a custom hosted web application',
    hostingTarget: 'You choose and operate it. Requires verification',
    builderRequirementSummary:
      'Judging generated code, testing behaviour, deploying, and owning security',
    overlapNote:
      'This is a build *method*, not a destination. It can produce a simple browser page or a full hosted application - the destination is chosen separately.',
  },
  'claude-code': {
    buildMethod: 'Claude Code in a development environment, with human review of every change',
    finalSolutionType:
      'Whatever you build: commonly a custom hosted web application, but not necessarily',
    hostingTarget: 'You choose and operate it. Requires verification',
    builderRequirementSummary:
      'Working in a development environment, reviewing changes, running tests, and operating the result',
    overlapNote:
      'This is a build *method*. It is not an alternative to a custom hosted web application - it is one way to build one. Choosing it does not settle where the result runs, who may reach it, or who maintains it.',
  },
  'custom-hosted': {
    buildMethod: 'Any coding method: AI-assisted, Claude Code, or a developer team',
    finalSolutionType: 'Custom hosted web application',
    hostingTarget: 'Required, with monitoring and backups. Requires verification',
    builderRequirementSummary:
      'Application development, permission design, deployment, and ongoing operations',
    overlapNote:
      'This is a *destination*, not a method. It says what the finished thing is; the build method above says how it gets built.',
  },
};
